In [7]:
import glob

all_files = glob.glob("*_youtube_trending_data.csv")
all_files

['CA_youtube_trending_data.csv',
 'GB_youtube_trending_data.csv',
 'IN_youtube_trending_data.csv',
 'RU_youtube_trending_data.csv',
 'BR_youtube_trending_data.csv',
 'KR_youtube_trending_data.csv',
 'US_youtube_trending_data.csv',
 'MX_youtube_trending_data.csv',
 'JP_youtube_trending_data.csv',
 'DE_youtube_trending_data.csv',
 'FR_youtube_trending_data.csv']

In [73]:
import pandas as pd
import os

df_list = []

for file in all_files:
    country = file.split("_")[0]   # BR, CA, DE...
    temp = pd.read_csv(file)
    temp["country"] = country
    df_list.append(temp)

df = pd.concat(df_list, ignore_index=True)

df.shape

(2905678, 17)

In [32]:
df.head()

,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,description,country
0,KX06ksuS6Xo,Diljit Dosanjh: CLASH (Official) Music Video |...,2020-08-11T07:30:02Z,UCZRdNleCgW-BGUJf-bbjzQg,Diljit Dosanjh,10,2020-08-12T00:00:00Z,clash diljit dosanjh|diljit dosanjh|diljit dos...,9140911,296541,6180,30059,https://i.ytimg.com/vi/KX06ksuS6Xo/default.jpg,False,False,CLASH official music video performed by DILJIT...,CA
1,J78aPJ3VyNs,I left youtube for a month and THIS is what ha...,2020-08-11T16:34:06Z,UCYzPXprvl5Y-Sf0g4vX-m6g,jacksepticeye,24,2020-08-12T00:00:00Z,jacksepticeye|funny|funny meme|memes|jacksepti...,2038853,353797,2628,40222,https://i.ytimg.com/vi/J78aPJ3VyNs/default.jpg,False,False,I left youtube for a month and this is what ha...,CA
2,M9Pmf9AB4Mo,Apex Legends | Stories from the Outlands – “Th...,2020-08-11T17:00:10Z,UC0ZV6M2THA81QT9hrVWJG3A,Apex Legends,20,2020-08-12T00:00:00Z,Apex Legends|Apex Legends characters|new Apex ...,2381688,146740,2794,16549,https://i.ytimg.com/vi/M9Pmf9AB4Mo/default.jpg,False,False,"While running her own modding shop, Ramya Pare...",CA
3,3C66w5Z0ixs,I ASKED HER TO BE MY GIRLFRIEND...,2020-08-11T19:20:14Z,UCvtRTOMP2TqYqu51xNrqAzg,Brawadis,22,2020-08-12T00:00:00Z,brawadis|prank|basketball|skits|ghost|funny vi...,1514614,156914,5857,35331,https://i.ytimg.com/vi/3C66w5Z0ixs/default.jpg,False,False,SUBSCRIBE to BRAWADIS ▶ http://bit.ly/Subscrib...,CA
4,VIUo6yapDbc,Ultimate DIY Home Movie Theater for The LaBran...,2020-08-11T15:10:05Z,UCDVPcEbVLQgLZX0Rt6jo34A,Mr. Kate,26,2020-08-12T00:00:00Z,The LaBrant Family|DIY|Interior Design|Makeove...,1123889,45803,964,2198,https://i.ytimg.com/vi/VIUo6yapDbc/default.jpg,False,False,Transforming The LaBrant Family's empty white ...,CA

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2905678 entries, 0 to 2905677
Data columns (total 17 columns):
 #   Column             Dtype
---  ------             -----
 0   video_id           object
 1   title              object
 2   publishedAt        object
 3   channelId          object
 4   channelTitle       object
 5   categoryId         int64
 6   trending_date      object
 7   tags               object
 8   view_count         int64
 9   likes              int64
 10  dislikes           int64
 11  comment_count      int64
 12  thumbnail_link     object
 13  comments_disabled  bool
 14  ratings_disabled   bool
 15  description        object
 16  country            object
dtypes: bool(2), int64(5), object(10)
memory usage: 338.1+ MB

In [34]:
df.isnull().sum()

video_id                 0
title                    0
publishedAt              0
channelId                0
channelTitle             1
categoryId               0
trending_date            0
tags                     0
view_count               0
likes                    0
dislikes                 0
comment_count            0
thumbnail_link           0
comments_disabled        0
ratings_disabled         0
description          88321
country                  0
dtype: int64

In [74]:
df['publishedAt'] = pd.to_datetime(df['publishedAt'], errors='coerce')
df['trending_date'] = pd.to_datetime(df['trending_date'], errors='coerce')

In [75]:
df['publish_year'] = df['publishedAt'].dt.year
df['publish_month'] = df['publishedAt'].dt.month

df['trend_year'] = df['trending_date'].dt.year
df['trend_month'] = df['trending_date'].dt.month

In [76]:
df['tags_list'] = df['tags'].apply(lambda x: str(x).split('|'))

In [77]:
from collections import Counter

tag_counter = Counter()
df['tags_list'].apply(tag_counter.update)
tag_counter.most_common(20)

[('[None]', 473297),
 ('funny', 67613),
 ('minecraft', 62573),
 ('vlog', 52910),
 ('comedy', 52476),
 ('challenge', 40380),
 ('football', 34534),
 ('highlights', 31251),
 ('tiktok', 25180),
 ('rap', 25058),
 ('video', 23219),
 ('soccer', 22957),
 ('Minecraft', 22807),
 ('fortnite', 22263),
 ('gaming', 22056),
 ('music', 21851),
 ('shorts', 21662),
 ('fun', 21433),
 ('news', 21131),
 ('BTS', 20751)]

In [78]:
import json

with open("US_category_id.json", "r") as f:
    data = json.load(f)

categories = {item['id']: item['snippet']['title'] for item in data['items']}
df['categoryId'] = df['categoryId'].astype(str)

df['category_name'] = df['categoryId'].map(categories)

In [79]:
df[['categoryId', 'category_name']].head()

  categoryId   category_name
0         10           Music
1         24   Entertainment
2         20          Gaming
3         22  People & Blogs
4         26   Howto & Style

In [80]:
df['country'].value_counts()

country
GB    268791
BR    268790
FR    268788
US    268787
JP    268778
CA    268742
DE    268736
MX    268598
KR    265754
IN    251277
RU    238637
Name: count, dtype: int64

In [42]:
df['category_name'].value_counts().head(15)

category_name
Entertainment            745782
Music                    437814
Gaming                   400807
People & Blogs           338997
Sports                   313361
Comedy                   153006
News & Politics          108594
Film & Animation          89271
Howto & Style             82411
Science & Technology      68737
Autos & Vehicles          64002
Education                 55508
Travel & Events           24621
Pets & Animals            17538
Nonprofits & Activism      5229
Name: count, dtype: int64

In [ ]:
pivot = df.pivot_table(
    index='country',
    columns='category_name',
    values='video_id',
    aggfunc='count'
)
pivot

category_name,Autos & Vehicles,Comedy,Education,Entertainment,Film & Animation,Gaming,Howto & Style,Music,News & Politics,Nonprofits & Activism,People & Blogs,Pets & Animals,Science & Technology,Sports,Travel & Events
country,,,,,,,,,,,,,,,
BR,2603,10380,3150,64925,3329,40437,2026,58413,4588,68,32594,323,3835,40716,1403
CA,6352,14427,7815,56896,9553,52546,8359,34545,8272,110,23216,1325,9221,33712,2393
DE,10773,7618,8106,69474,4353,31027,9225,43125,9538,146,27821,892,9864,34746,2028
FR,8764,22717,7738,64800,5990,36885,10327,47800,7249,136,14789,657,8677,30347,1912
GB,6667,12101,6593,58005,7868,45956,5795,33293,6682,107,24541,1069,8524,48941,2649
IN,1597,18155,5955,98264,6491,14735,8065,32609,7543,90,41079,110,7566,7306,1712
JP,4259,12281,1290,88336,11389,38733,8020,37369,5434,170,31315,4347,1161,23946,728
KR,2178,17049,4227,90079,7108,11236,11350,30500,10267,561,44516,5500,3924,20496,6763
MX,2488,9665,1941,63158,7229,42128,6642,61626,10307,175,33959,156,2099,25385,1640
RU,12829,15430,2038,37911,15038,33882,5502,15136,29045,3546,42514,1937,5710,16439,1680
US,5492,13183,6655,53934,10923,53242,7100,43398,9669,120,22653,1222,8156,31327,1713

In [ ]:
df['category_name'].value_counts().head(15)

category_name
Entertainment            745782
Music                    437814
Gaming                   400807
People & Blogs           338997
Sports                   313361
Comedy                   153006
News & Politics          108594
Film & Animation          89271
Howto & Style             82411
Science & Technology      68737
Autos & Vehicles          64002
Education                 55508
Travel & Events           24621
Pets & Animals            17538
Nonprofits & Activism      5229
Name: count, dtype: int64

In [87]:

data1 = df[(df['trend_year'] == 2023) & (df['trend_month'] <= 3)]

print(data1.shape)  # ~530K olur

(194159, 23)

In [69]:
data1.shape

(795502, 23)

In [70]:
# 2022 veri özeti
print(f"Toplam video sayısı: {len(data1)}")
print(f"Tarih aralığı: {data1['trending_date'].min()} - {data1['trending_date'].max()}")
print(f"\nÜlke dağılımı:")
print(data1['country'].value_counts())
print(f"\nKategori dağılımı:")
print(data1['category_name'].value_counts().head(10))

Toplam video sayısı: 795502
Tarih aralığı: 2022-01-01 00:00:00+00:00 - 2022-12-31 00:00:00+00:00

Ülke dağılımı:
country
KR    73000
CA    72999
US    72999
MX    72999
FR    72999
GB    72998
BR    72998
DE    72995
JP    72994
IN    71056
RU    67465
Name: count, dtype: int64

Kategori dağılımı:
category_name
Entertainment           199912
Gaming                  130923
Music                   110520
People & Blogs           97248
Sports                   79602
Comedy                   43138
News & Politics          31437
Film & Animation         23235
Howto & Style            20056
Science & Technology     15891
Name: count, dtype: int64

In [71]:
# Sadece 5-6 ülke seç - kültürel çeşitlilik yine korunur
selected_countries = ['US', 'GB', 'JP', 'KR', 'BR', 'DE']
df = df[df['country'].isin(selected_countries)]

print(df.shape)  # ~400K-450K olur

(1609636, 23)